booking:
  property: Suplier dev  Updated
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supplierDB525?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8087

app:
  nombre: Alejandro