booking:
  property: Suplier dev  Updated
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supplierDB525?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    vault:
      application-name: service
      host: localhost
      port: 8200
      scheme: http
      authentication: TOKEN
      token: 00000000-0000-0000-0000-000000000000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8087

app:
  nombre: Alejandro Nuevo 3

